services:
  backend:
    container_name: moneat_server
    # in case we have an error
    restart: always
    image: moneat_server
    build:
      context: ./
      dockerfile: server.dockerfile
    ports:
      - 3002:3002
      - 5555:5555
    environment:
      - DATABASE_URL=${DB_URL}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - ./setup.js:/app/setup.js
      - ./node_modules:/app/node_modules

  db:
    container_name: moneat_db
    image: postgres:15
    # in case we have an error
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres_data: {}
